---
id: oedo04
base_name: one-gem-one-year
tags: []
presentation_date: 2014/04/19
version: 1.0.0
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: Kunihiko Ito
  email: kuni.110.92@gmail.com
  rubygems_user: kunitoo
  slideshare_user: kunitoo
  speaker_deck_user: kunitoo
